export const achievements = [
  {
    id: 1,
    name: "10 Pets born",
    description: "Create 10 pets",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 10,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 2,
    name: "10 Pets killed",
    description: "Delete 10 pets",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 10,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 3,
    name: "1000 Coins earned",
    description: "Earn 1000 coins in minigames",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 1000,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 4,
    name: "100 Feeds",
    description: "Feed your pets 100 times",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 100,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 5,
    name: "100 Plays",
    description: "Play 100 times with your pets",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 100,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 6,
    name: "100 Sleeps",
    description: "Let your pets sleep 100 times",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 100,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 7,
    name: "Obstacle Jumper survivor",
    description: "Manage to survive 3min in Obstacle Jumper",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 180,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 8,
    name: "Merge master",
    description: "Get a score of 2048 in Merge Pets",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 2048,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 9,
    name: "Treasure hunter",
    description: "Get a score of 150 in Tresure Hunter",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 150,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 10,
    name: "Doemser food is good food",
    description: "Feed the secret doemser food 10 times",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 10,
    currentAmount: 0,
    unlocked: false,
  },
  {
    id: 11,
    name: "It's not my fault",
    description: "Your pet gets run over by a car",
    icon: "/assets/icons/trophy.png",
    achievementGoal: 1,
    currentAmount: 0,
    unlocked: false,
  },
];
