const initialMyPets = [
  {
    id: "7da41d54-8213-424d-8484-5f77e1cfe491",
    type: "chameleon",
    name: "Krischan",
    image: "/assets/images/pets/chameleon.png",
    health: 100,
    hunger: 100,
    happiness: 100,
    energy: 100,
    isDead: false,
    level: 1,
    xp: 0,
  },
  {
    id: "2",
    type: "duck",
    name: "Nina",
    image: "/assets/images/pets/duck.png",
    health: 100,
    hunger: 100,
    happiness: 100,
    energy: 100,
    isDead: false,
    level: 1,
    xp: 0,
  },
  {
    id: "3",
    type: "owl",
    name: "Markus",
    image: "/assets/images/pets/owl.png",
    health: 100,
    hunger: 100,
    happiness: 100,
    energy: 100,
    isDead: false,
    level: 1,
    xp: 0,
  },
];

export default initialMyPets;
