export const foods = [
  {
    id: 1,
    name: "Broccoli",
    description: "This is a broccoli.",
    cost: 1,
    value: 2,
    image: "/assets/images/food/broccoli.png",
  },
  {
    id: 2,
    name: "Canned Food",
    description: "This is canned food.",
    cost: 2,
    value: 4,
    image: "/assets/images/food/canned-food.png",
  },
  {
    id: 3,
    name: "Dog Bowl",
    description: "This is a dog bowl.",
    cost: 3,
    value: 5,
    image: "/assets/images/food/dog-bowl.png",
  },
  {
    id: 4,
    name: "Donut",
    description: "This is a donut.",
    cost: 5,
    value: 8,
    image: "/assets/images/food/donut.png",
  },
  {
    id: 5,
    name: "Bubble Tea",
    description: "This is a bubble tea.",
    cost: 6,
    value: 11,
    image: "/assets/images/food/bubble-tea.png",
  },
  {
    id: 6,
    name: "Cupcake",
    description: "This is a cupcake.",
    cost: 7,
    value: 13,
    image: "/assets/images/food/cupcake.png",
  },
  {
    id: 7,
    name: "Hot Soup",
    description: "This is a hot soup.",
    cost: 10,
    value: 19,
    image: "/assets/images/food/hot-soup.png",
  },
  {
    id: 8,
    name: "Hamburger",
    description: "This is a hamburger.",
    cost: 14,
    value: 30,
    image: "/assets/images/food/hamburger.png",
  },
  {
    id: 9,
    name: "Spaghetti",
    description: "This is a spaghetti.",
    cost: 19,
    value: 40,
    image: "/assets/images/food/spaghetti.png",
  },
  {
    id: 10,
    name: "Lobster",
    description: "This is a lobster.",
    cost: 45,
    value: 80,
    image: "/assets/images/food/lobster.png",
  },
];

export const toys = [
  {
    id: 1,
    name: "Branch",
    description: "This is a Branch.",
    cost: 0,
    value: 3,
    image: "/assets/images/toy/branch.png",
  },
  {
    id: 2,
    name: "Bone",
    description: "This is a Bone.",
    cost: 50,
    value: 7,
    image: "/assets/images/toy/bone.png",
  },
  {
    id: 3,
    name: "Wool Ball",
    description: "This is a Wool Ball.",
    cost: 100,
    value: 11,
    image: "/assets/images/toy/wool-ball.png",
  },
  {
    id: 4,
    name: "Rope Knot",
    description: "This is a Rope Knot.",
    cost: 150,
    value: 15,
    image: "/assets/images/toy/rope-knot.png",
  },
  {
    id: 5,
    name: "Toy on a Stick",
    description: "This is a Toy on a Stick.",
    cost: 250,
    value: 21,
    image: "/assets/images/toy/toy-on-a-stick.png",
  },
  {
    id: 6,
    name: "Ball",
    description: "This is a Ball.",
    cost: 300,
    value: 35,
    image: "/assets/images/toy/ball.png",
  },
];

export const clothes = [
  {
    id: 0,
    name: "None",
    description: "",
    cost: 0,
    yOffset: 0,
    image: "/assets/icons/no-stopping.png",
  },
  {
    id: 1,
    name: "Day Bed Daisy",
    description: "This is a day bed.",
    cost: 90,
    yOffset: -45,
    image: "/assets/images/clothes/day-bed-red-yellow.png",
  },
  {
    id: 2,
    name: "Day Bed Casper",
    description: "This is a day bed.",
    cost: 120,
    yOffset: -20,
    image: "/assets/images/clothes/day-bed-blue.png",
  },
  {
    id: 3,
    name: "Pet Hut Vicky",
    description: "This is a pet hut.",
    cost: 230,
    yOffset: 60,
    image: "/assets/images/clothes/pet-house-yellow.png",
  },
  {
    id: 4,
    name: "Pet Hut Tom",
    description: "This is a pet hut.",
    cost: 310,
    yOffset: 60,
    image: "/assets/images/clothes/pet-house-brown.png",
  },
  {
    id: 5,
    name: "Fish Bowl Dorie",
    description: "This is a fish bowl.",
    cost: 50,
    yOffset: -15,
    image: "/assets/images/clothes/fish-bowl.png",
  },
];
